name: fluttermg4_tugas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'
dependencies:
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  http: ^0.13.5
  flutter_spinkit: ^5.0.0
  image_picker: ^0.8.5+4
  file_picker: ^4.0.0
  path: ^1.8.2
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.3
  cupertino_icons: ^1.0.6
  rename: ^3.0.2
  lottie: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/school.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/school.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/school.png
    - assets/opang.jpg
    - assets/lottie/Animation - 1728840787980.json
